import dash
from dash import Dash, html, Input, Output
from dash import dcc
from dash import dash_table
from dash.dependencies import Input, Output

import dash_bootstrap_components as dbc

# --------------------
# Register this page
# --------------------

dash.register_page(__name__)

layout = dbc.Container(
    [
        dbc.Row(
            [
                dbc.Col(
                    [
                        html.H1("Privacy and data protection", className="display-3"),
                        html.P(
                            "We take your privacy seriously.",
                            className="lead",
                        ),
                        html.P(
                            "This privacy and data protection policy (“Policy”) outlines the personal information that we (“enviConnect”, “we”, “us” or “our”) gathers, how we use that personal information, and the options you have to access, correct, or delete such personal information."
                        ),
                        # Service provider
                        html.H2("Service Provider"),
                        # Cookies
                        html.H2("Cookies, scripts, and web beacons"),
                        html.P(
                            "Cookies are small text files that can be generated by web sites to store information on your computer. "
                        ),
                    ],
                    class_name="col-12 col-md-9 mt-2"
                )
            ]
        )
    ]
)
